CREATE TABLE IF NOT EXISTS Genre (
id SERIAL PRIMARY KEY,
name VARCHAR(60) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS Artist (
id SERIAL PRIMARY KEY,
name VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS GenreArtist (
id_genre INTEGER REFERENCES Genre(id),
id_artist INTEGER REFERENCES Artist(id),
CONSTRAINT pk PRIMARY KEY (id_genre, id_artist)
);

CREATE TABLE IF NOT EXISTS Album (
id SERIAL PRIMARY KEY,
album_name VARCHAR(100) NOT NULL,
release INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ArtistAlbum(
id_artist INTEGER REFERENCES Artist(id),
id_album INTEGER REFERENCES Album(id),
CONSTRAINT aa PRIMARY KEY (id_artist, id_album)
);

CREATE TABLE IF NOT EXISTS Track (
id SERIAL PRIMARY KEY,
name VARCHAR(200) NOT NULL,
time TIME NOT NULL,
album_id INTEGER REFERENCES Album(id)
);

CREATE TABLE IF NOT EXISTS Collection(
id SERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL,
year INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS CollectionTrack(
id_track INTEGER REFERENCES Track(id),
id_collection INTEGER REFERENCES Collection(id),
CONSTRAINT ct PRIMARY KEY (id_track, id_collection)
);